### ISSUE TITLE
Payment freeze with java kernal

### ISSUE THREAD

**Issue by equ1miner** [aionnetwork/aion_pool2#34]
Blocks failed to unlock but does unlock ok when run with rust kernal

[2020-01-23 05:09:36.5644] [I] [PayoutManager] Online 
[2020-01-23 05:09:36.5671] [I] [StatsRecorder] Online 
[2020-01-23 05:09:36.5721] [I] [PayoutManager] Processing payments for pool aion 
[2020-01-23 05:09:36.6099] [I] [aion] [Pool] Launching ... 
[2020-01-23 05:09:36.6578] [D] [DaemonClient] ExecuteCmdAnyAsync(ping) 
[2020-01-23 05:09:36.7013] [D] [DaemonClient] [DaemonClient] Starting RPC Request to ping 
[2020-01-23 05:09:36.7479] [D] [DaemonClient] [DaemonClient] RPC Request to ping actually took 45 ms 
[2020-01-23 05:09:36.7652] [D] [DaemonClient] ExecuteCmdAnyAsync(validateaddress) 
[2020-01-23 05:09:36.7719] [D] [DaemonClient] [DaemonClient] Starting RPC Request to validateaddress 
[2020-01-23 05:09:36.7719] [D] [DaemonClient] [DaemonClient] RPC Request to validateaddress actually took 1 ms 
[2020-01-23 05:09:36.7888] [I] [aion] [Job Manager] Launching ... 
[2020-01-23 05:09:36.7984] [I] [aion] [Job Manager] All daemons online 
[2020-01-23 05:09:36.8273] [D] [aion] [Job Manager] GetBlockTemplateAsync() 
[2020-01-23 05:09:36.8273] [D] [DaemonClient] ExecuteCmdAnyAsync(getblocktemplate) 
[2020-01-23 05:09:36.8273] [D] [DaemonClient] [DaemonClient] Starting RPC Request to getblocktemplate 
[2020-01-23 05:09:36.8273] [D] [DaemonClient] [DaemonClient] RPC Request to getblocktemplate actually took 1 ms 
[2020-01-23 05:09:36.8340] [I] [aion] [Job Manager] Online 
[2020-01-23 05:09:37.2125] [D] [BlockRepository] GetDistinctPendingBlocksForPool(aion) 
[2020-01-23 05:09:37.5735] [D] [DaemonClient] ExecuteCmdAllAsync(eth_getBlockByNumber) 
[2020-01-23 05:09:37.5748] [D] [DaemonClient] [DaemonClient] Starting RPC Request to eth_getBlockByNumber 
[2020-01-23 05:09:37.5806] [D] [DaemonClient] [DaemonClient] RPC Request to eth_getBlockByNumber actually took 5 ms 
[2020-01-23 05:09:37.6174] [E] [PayoutManager] [aion] Payment processing failed Newtonsoft.Json.JsonSerializationException: Error converting value "0x4fa867" to type 'System.Nullable`1[System.UInt64]'. Path 'transactions[0].blockNumber'. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseUInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in /home/aionpool/aion_pool2/aion_pool/src/MiningCore/DaemonInterface/DaemonClient.cs:line 420
   at System.Linq.Enumerable.<SelectIterator>d__154`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at MiningCore.DaemonInterface.DaemonClient.<ExecuteCmdAllAsync>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Aion.AionPayoutHandler.<ClassifyBlocksAsync>d__7.MoveNext() in /home/aionpool/aion_pool2/aion_pool/src/MiningCore/Blockchain/Aion/AionPayoutHandler.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<UpdatePoolBalancesAsync>d__12.MoveNext() in /home/aionpool/aion_pool2/aion_pool/src/MiningCore/Payments/PayoutManager.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in /home/aionpool/aion_pool2/aion_pool/src/MiningCore/Payments/PayoutManager.cs:line 95    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at MiningCore.DaemonInterface.DaemonClient.MapDaemonResponse[TResponse](Int32 i, Task`1 x, Boolean throwOnError) in /home/aionpool/aion_pool2/aion_pool/src/MiningCore/DaemonInterface/DaemonClient.cs:line 420
   at System.Linq.Enumerable.<SelectIterator>d__154`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at MiningCore.DaemonInterface.DaemonClient.<ExecuteCmdAllAsync>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Aion.AionPayoutHandler.<ClassifyBlocksAsync>d__7.MoveNext() in /home/aionpool/aion_pool2/aion_pool/src/MiningCore/Blockchain/Aion/AionPayoutHandler.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<UpdatePoolBalancesAsync>d__12.MoveNext() in /home/aionpool/aion_pool2/aion_pool/src/MiningCore/Payments/PayoutManager.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in /home/aionpool/aion_pool2/aion_pool/src/MiningCore/Payments/PayoutManager.cs:line 95
[2020-01-23 05:09:46.5813] [I] [StatsRecorder] Updating hashrates for pool aion 
[2020-01-23 05:09:46.5959] [D] [ShareRepository] GetHashAccumulationBetweenCreated(aion) 
[2020-01-23 05:09:46.6335] [D] [StatsRepository] InsertPoolStats() 
[2020-01-23 05:09:56.8912] [D] [aion] [Job Manager] UpdateJobAsync() 
[2020-01-23 05:09:56.8912] [D] [aion] [Job Manager] GetBlockTemplateAsync() 
[2020-01-23 05:09:56.8912] [D] [DaemonClient] ExecuteCmdAnyAsync(getblocktemplate) 
[2020-01-23 05:09:56.8912] [D] [DaemonClient] [DaemonClient] Starting RPC Request to getblocktemplate 
[2020-01-23 05:09:56.8912] [D] [DaemonClient] [DaemonClient] RPC Request to getblocktemplate actually took 1 ms 
[2020-01-23 05:09:56.9321] [D] [aion] [Job Manager] UpdateJob() 
[2020-01-23 05:10:16.8673] [D] [aion] [Job Manager] UpdateJobAsync() 
[2020-01-23 05:10:16.8673] [D] [aion] [Job Manager] GetBlockTemplateAsync() 
[2020-01-23 05:10:16.8673] [D] [DaemonClient] ExecuteCmdAnyAsync(getblocktemplate) 
[2020-01-23 05:10:16.8673] [D] [DaemonClient] [DaemonClient] Starting RPC Request to getblocktemplate 
[2020-01-23 05:10:16.8673] [D] [DaemonClient] [DaemonClient] RPC Request to getblocktemplate actually took 1 ms 
[2020-01-23 05:10:16.8673] [D] [aion] [Job Manager] UpdateJob() 
[2020-01-23 05:10:16.8815] [D] [DaemonClient] ExecuteCmdAnyAsync(getdifficulty) 
[2020-01-23 05:10:16.8815] [D] [DaemonClient] [DaemonClient] Starting RPC Request to getdifficulty 
[2020-01-23 05:10:16.8829] [D] [DaemonClient] [DaemonClient] RPC Request to getdifficulty actually took 0 ms 
[2020-01-23 05:10:16.8887] [D] [DaemonClient] ExecuteCmdAnyAsync(getMinerStats) 
[2020-01-23 05:10:16.8887] [D] [DaemonClient] [DaemonClient] Starting RPC Request to getMinerStats 
[2020-01-23 05:10:16.8887] [D] [DaemonClient] [DaemonClient] RPC Request to getMinerStats actually took 0 ms 
[2020-01-23 05:10:16.8950] [I] [aion] [Job Manager] New block 5220458 detected

**Comment by aionfarbod** [comment]
@AionJayT  Can you please check this issue Payment freeze, they have problem processing payments

**Comment by equ1miner** [comment]
Any change someone can look we have an issue again


[PayoutManager] [aion] Payment processing failed Newtonsoft.Json.JsonSerializationException: Error converting value "0x52448e" to type 'System.Nullable`1[System.UInt64]'. Path 'transactions[0].blockNumber'. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseUInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at MiningCore.Blockchain.Aion.AionPayoutHandler.<FetchBlocks>d__11.MoveNext() in /home/aionm/extra/aion_pool/src/MiningCore/Blockchain/Aion/AionPayoutHandler.cs:line 259
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Aion.AionPayoutHandler.<ClassifyBlocksAsync>d__7.MoveNext() in /home/aionm/extra/aion_pool/src/MiningCore/Blockchain/Aion/AionPayoutHandler.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<UpdatePoolBalancesAsync>d__12.MoveNext() in /home/aionm/extra/aion_pool/src/MiningCore/Payments/PayoutManager.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in /home/aionm/extra/aion_pool/src/MiningCore/Payments/PayoutManager.cs:line 95    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at MiningCore.Blockchain.Aion.AionPayoutHandler.<FetchBlocks>d__11.MoveNext() in /home/aionm/extra/aion_pool/src/MiningCore/Blockchain/Aion/AionPayoutHandler.cs:line 259
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Blockchain.Aion.AionPayoutHandler.<ClassifyBlocksAsync>d__7.MoveNext() in /home/aionm/extra/aion_pool/src/MiningCore/Blockchain/Aion/AionPayoutHandler.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<UpdatePoolBalancesAsync>d__12.MoveNext() in /home/aionm/extra/aion_pool/src/MiningCore/Payments/PayoutManager.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MiningCore.Payments.PayoutManager.<ProcessPoolsAsync>d__11.MoveNext() in /home/aionm/extra/aion_pool/src/MiningCore/Payments/PayoutManager.cs:line 95
