### ISSUE TITLE
Error on newly built pool node

### ISSUE THREAD

**Issue by POW-onl** [aionnetwork/aion_pool2#36]
Everything seems to be working, in testing phases but the output keeps giving me a string of this issue mentioned below and then goes back to std out.  Line 35 has to do with ILogger call to logger of AionJob.cs

[2020-03-02 18:53:03.7255] [E] [AionOne] [Job Manager] Error during UpdateJob System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Aion.AionJob..ctor(String id, AionBlockTemplate blockTemplate, ILogger logger, DaemonClient daemon) in /home/ubuntu/aion_pool2/aion_pool/src/MiningCore/Blockchain/Aion/AionJob.cs:line 35
   at MiningCore.Blockchain.Aion.AionJobManager.UpdateJob(AionBlockTemplate blockTemplate) in /home/ubuntu/aion_pool2/aion_pool/src/MiningCore/Blockchain/Aion/AionJobManager.cs:line 230    at MiningCore.Blockchain.Aion.AionJob..ctor(String id, AionBlockTemplate blockTemplate, ILogger logger, DaemonClient daemon) in /home/ubuntu/aion_pool2/aion_pool/src/MiningCore/Blockchain/Aion/AionJob.cs:line 35
   at MiningCore.Blockchain.Aion.AionJobManager.UpdateJob(AionBlockTemplate blockTemplate) in /home/ubuntu/aion_pool2/aion_pool/src/MiningCore/Blockchain/Aion/AionJobManager.cs:line 230

**Comment by JimVanEeden** [comment]
I have the same problem. I'm trying to set up the pool for solo mining, but it's giving me the same error.

```
[2020-03-05 10:11:47.0165] [E] [aion-1] [Job Manager] Error during UpdateJob System.NullReferenceException: Object reference not set to an instance of an object.
   at MiningCore.Blockchain.Aion.AionJob..ctor(String id, AionBlockTemplate blockTemplate, ILogger logger, DaemonClient daemon) in /home/jim/aion-home/aion_pool2/aion_pool/src/MiningCore/Blockchain/Aion/AionJob.cs:line 35
   at MiningCore.Blockchain.Aion.AionJobManager.UpdateJob(AionBlockTemplate blockTemplate) in /home/jim/aion-home/aion_pool2/aion_pool/src/MiningCore/Blockchain/Aion/AionJobManager.cs:line 230
```

**Comment by POW-onl** [comment]
@JimVanEeden,
  I was talking to others in the community.  It is a known issue.  It is the POS blocks!  The mining core needs an update as it doesn't know how to handle them.

**Comment by JimVanEeden** [comment]
Are current mining pools running this software with this error?

**Comment by POW-onl** [comment]
@JimVanEeden 
From what I was told; yes but don't quote me.
