### ISSUE TITLE
Payouts issue stops mined blocks from processing and adding to balance.

### ISSUE THREAD

**Issue by Knevil** [aionnetwork/aion_pool2#4]
E] [PayoutManager] [aion] Payment processing failed System.OverflowException: Value was either too large or too small for a Decimal.
at System.Decimal..ctor(Double value)
at MiningCore.Payments.PaymentSchemes.PPLNSPaymentScheme.CalculateRewards(PoolConfig poolConfig, Decimal window, Block block, Decimal blockReward, Dictionary2 shares, Dictionary2 rewards)
at MiningCore.Payments.PaymentSchemes.PPLNSPaymentScheme.UpdateBalancesAsync(IDbConnection con, IDbTransaction tx, PoolConfig poolConfig, IPayoutHandler payoutHandler, Block block, Decimal blockReward) in /home/foundry/aion_pool2/aion_pool/src/MiningCore/Payments/PaymentSchemes/PPLNSPaymentScheme.cs:line 91
at MiningCore.Payments.PayoutManager.<>c__DisplayClass12_1.<b__4>d.MoveNext() in sourcedir/aion_pool2/aion_pool/src/MiningCore/Payments/PayoutManager.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
at MiningCore.Extensions.ConnectionFactoryExtensions.RunTxAsync(IConnectionFactory factory, Func3 action, Boolean autoCommit, IsolationLevel isolation) in sourcedir/aion_pool2/aion_pool/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 214 at MiningCore.Payments.PayoutManager.UpdatePoolBalancesAsync(PoolConfig pool, IPayoutHandler handler, IPayoutScheme scheme) in sourcedir/aion_pool2/aion_pool/src/MiningCore/Payments/PayoutManager.cs:line 121 at MiningCore.Payments.PayoutManager.ProcessPoolsAsync() in sourcedir/aion_pool2/aion_pool/src/MiningCore/Payments/PayoutManager.cs:line 95 at System.Decimal..ctor(Double value) at MiningCore.Payments.PaymentSchemes.PPLNSPaymentScheme.CalculateRewards(PoolConfig poolConfig, Decimal window, Block block, Decimal blockReward, Dictionary2 shares, Dictionary2 rewards) at MiningCore.Payments.PaymentSchemes.PPLNSPaymentScheme.UpdateBalancesAsync(IDbConnection con, IDbTransaction tx, PoolConfig poolConfig, IPayoutHandler payoutHandler, Block block, Decimal blockReward) in sourcedir/aion_pool2/aion_pool/src/MiningCore/Payments/PaymentSchemes/PPLNSPaymentScheme.cs:line 91 at MiningCore.Payments.PayoutManager.<>c__DisplayClass12_1.<<UpdatePoolBalancesAsync>b__4>d.MoveNext() in sourcedir/aion_pool2/aion_pool/src/MiningCore/Payments/PayoutManager.cs:line 139 --- End of stack trace from previous location where exception was thrown --- at MiningCore.Extensions.ConnectionFactoryExtensions.RunTxAsync(IConnectionFactory factory, Func3 action, Boolean autoCommit, IsolationLevel isolation) in sourcedir/aion_pool2/aion_pool/src/MiningCore/Extensions/ConnectionFactoryExtensions.cs:line 214
at MiningCore.Payments.PayoutManager.UpdatePoolBalancesAsync(PoolConfig pool, IPayoutHandler handler, IPayoutScheme scheme) in sourcedir/aion_pool2/aion_pool/src/MiningCore/Payments/PayoutManager.cs:line 121
at MiningCore.Payments.PayoutManager.ProcessPoolsAsync() in sourcedir/aion_pool2/aion_pool/src/MiningCore/Payments/PayoutManager.cs:line 95

**Comment by Knevil** [comment]
HashPowerPool.com have encountered the exact same issue twice now

**Comment by centrys-alin** [comment]
duplicate from: https://github.com/aionnetwork/aion_pool2/issues/3
